sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ashutosh3309/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ashutosh3309/react-test npm test
 
after_success:
  - docker build -t ashutosh3309/multi-client ./client
  - docker build -t ashutosh3309/multi-nginx ./nginx
  - docker build -t ashutosh3309/multi-server ./server
  - docker build -t ashutosh3309/multi-worker ./worker
  # Log in to the docker CLI
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ashutosh3309/multi-client
  - docker push ashutosh3309/multi-nginx
  - docker push ashutosh3309/multi-server
  - docker push ashutosh3309/multi-worker
